---
- hosts: local
  tasks:
    - name: Generate configuration file
      template: src=/home/melphick/pynet/week5/ansible/switch_template.j2
                dest=/home/melphick/pynet/week5/ansible/{{item.hostname}}.txt
      with_items:
        - {hostname: switch_1, ip_addr: 1.1.1.1}
        - {hostname: switch_2, ip_addr: 1.1.1.2}
        - {hostname: switch_3, ip_addr: 1.1.1.3}
        - {hostname: switch_4, ip_addr: 1.1.1.4}
        - {hostname: switch_5, ip_addr: 1.1.1.5}
